apiVersion: v1
kind: Service
metadata:
  name: {{ include "balkanid.fullname" . }}
spec:
  type: {{ .Values.api.service.type }}
  selector: { app: {{ include "balkanid.name" . }} }
  ports: [{ name: http, port: {{ .Values.api.service.port }}, targetPort: http }]
