import { useEffect, useState } from 'react'
import { Clipboard, Link2, X } from 'lucide-react'
import { api, ShareAccess } from './api'

type Props = { kind: 'file' | 'folder'; id: string; name: string; csrf: string; onClose: () => void }

export default function ShareDialog({ kind, id, name, csrf, onClose }: Props) {
  const folder = kind === 'folder'
  const [email, setEmail] = useState(''), [permission, setPermission] = useState('view')
  const [access, setAccess] = useState<ShareAccess[]>([]), [publicLink, setPublicLink] = useState('')
  const [copied, setCopied] = useState(false), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const loadAccess = async () => { try { setAccess((await api.shareAccess(id, folder)).items) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to load access') } }
  useEffect(() => { void loadAccess() }, [id, folder])
  const makePublic = async () => { setBusy(true); try { const r = folder ? await api.publicFolderShare(id, csrf) : await api.publicShare(id, csrf); setPublicLink(`${window.location.origin}/public/${r.token}`); setCopied(false) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to create public link') } finally { setBusy(false) } }
  const makePrivate = async () => { setBusy(true); try { if (folder) await api.revokePublicFolderShare(id, csrf); else await api.revokeShare(id, csrf); setPublicLink(''); setMessage('Public access removed. This item is private.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to remove public access') } finally { setBusy(false) } }
  const addAccess = async () => { if (!email.trim()) { setMessage('Enter a recipient email.'); return }; setBusy(true); try { if (folder) await api.directFolderShare(id, email.trim(), permission, csrf); else await api.directShare(id, email.trim(), permission, csrf); setEmail(''); setMessage('Access granted.'); await loadAccess() } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to share with this user') } finally { setBusy(false) } }
  const removeAccess = async (item: ShareAccess) => { if (!window.confirm(`Remove ${item.recipientEmail}'s access?`)) return; setBusy(true); try { await api.revokeDirectShare(item.id, folder, csrf); setMessage('Access removed.'); await loadAccess() } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to remove access') } finally { setBusy(false) } }
  return <div className="modal-backdrop" onClick={onClose}><section className="share-dialog" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close sharing dialog"><X /></button><p className="eyebrow">SHARING</p><h2>Share “{name}”</h2><div className="share-section"><label>Add people with access<input value={email} onChange={e => setEmail(e.target.value)} placeholder="recipient@example.com" type="email" /></label><select value={permission} onChange={e => setPermission(e.target.value)} aria-label="Permission"><option value="view">Can view</option><option value="download">Can download</option></select><button className="primary" disabled={busy} onClick={() => void addAccess()}>Share</button></div><div className="share-section"><strong>People with access</strong>{access.length === 0 ? <p className="muted">Only you have access.</p> : access.map(item => <div className="access-row" key={item.id}><div><strong>{item.recipientName}</strong><small>{item.recipientEmail} · Can {item.permission}</small></div><button className="secondary" disabled={busy} onClick={() => void removeAccess(item)}>Remove</button></div>)}</div><div className="share-section"><strong>General access</strong>{publicLink ? <div className="public-access"><span>Anyone with the link</span><div className="link-row"><code>{publicLink}</code><button className="icon-button" onClick={() => { void navigator.clipboard.writeText(publicLink); setCopied(true) }} title="Copy link">{copied ? 'Copied' : <Clipboard />}</button></div><button className="secondary" disabled={busy} onClick={() => void makePrivate()}>Make private</button></div> : <><p className="muted">Restricted · Only people with access can open this link.</p><button className="secondary" disabled={busy} onClick={() => void makePublic()}><Link2 /> Anyone with the link</button></>}</div>{message && <p className="muted share-message">{message}</p>}</section></div>
}
