import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Stats } from './api'

const formatBytes = (value: number) => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`

export default function StorageStatsVisual({ stats }: { stats: Stats }) {
  const savings = Math.max(0, stats.savingsBytes)
  const quotaPercent = stats.quotaBytes ? Math.min(100, stats.deduplicatedBytes * 100 / stats.quotaBytes) : 0
  const composition = [{ name: 'Physical used', value: stats.deduplicatedBytes }, { name: 'Saved', value: savings }]
  return <section className="user-storage-analytics"><div className="analytics-heading"><div><p className="eyebrow">PERSONAL STORAGE ANALYTICS</p><h2>Your storage at a glance</h2></div><span className="live-pill"><i /> Live</span></div><div className="user-chart-grid"><article className="user-chart-card"><h3>Original vs deduplicated</h3><ResponsiveContainer width="100%" height={190}><BarChart data={[{ name: 'Storage', original: stats.originalBytes, deduplicated: stats.deduplicatedBytes }]} margin={{ top: 12, right: 8, left: 0, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e4edf0" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#71849a', fontSize: 11 }} /><YAxis tick={{ fill: '#71849a', fontSize: 11 }} tickFormatter={value => formatBytes(Number(value))} /><Tooltip formatter={value => formatBytes(Number(value))} /><Bar dataKey="original" name="Original" fill="#b8c9d2" radius={[6, 6, 0, 0]} /><Bar dataKey="deduplicated" name="Deduplicated" fill="#147f83" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></article><article className="user-chart-card"><h3>Deduplication impact</h3><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={composition} dataKey="value" nameKey="name" innerRadius={52} outerRadius={72} paddingAngle={4}>{composition.map((entry, index) => <Cell key={entry.name} fill={index === 0 ? '#147f83' : '#72b8ab'} />)}</Pie><Tooltip formatter={value => formatBytes(Number(value))} /></PieChart></ResponsiveContainer><p className="chart-caption">{stats.savingsPercent.toFixed(1)}% saved · {formatBytes(savings)}</p></article><article className="user-chart-card quota-card"><h3>Quota usage</h3><div className="quota-value"><strong>{formatBytes(stats.deduplicatedBytes)}</strong><span>of {formatBytes(stats.quotaBytes)}</span></div><div className="quota-track"><span style={{ width: `${quotaPercent}%` }} /></div><p className="chart-caption">{quotaPercent.toFixed(1)}% of your quota used</p></article></div></section>
}
